### ISSUE TITLE
Add support for traffic

### ISSUE THREAD

**Issue by i00** [aerialls/synology-srm#11]
Is it possible to add support for traffic statistics.. so I can get the amout transferred yesterday for instance?

**Comment by aerialls** [comment]
Hi, thanks for the issue.

It's probably possible but the issue is that Synology does not provide a public documentation regarding the SRM API. So we need to find the API endpoint ourselves.

**Comment by aerialls** [comment]
Done with c13d59e87977f30ea5824a7cf7f8a7996acb0468

**Comment by aerialls** [comment]
Released with version `0.1.4`.
