### ISSUE TITLE
Calling method 'export' at endpoint SYNO.Core.Certificate returns error=5503

### ISSUE THREAD

**Issue by stylon** [aerialls/synology-srm#13]
In an attempt to automate distributing Let's Encrypt certificates to machines on the local network, I fail to access the 'export' method at SYNO.Core.Certificate. Other methods do work (e.g. 'list' or 'renew' at the sub-API SYNO.Core.Certificate.LetsEncrypt). I tried to access it this way:

`self.http.call(path='entry.cgi', api='SYNO.Core.Certificate', method='export', version=1)`

And this is what I get:

`File "/usr/local/lib/python3.5/dist-packages/synology_srm/http.py", line 167, in call
    message,
synology_srm.http.SynologyApiError: Unknown API error, please check the documentation (error=5503)
`

On the UI, clicking on the 'Export' button creates an archive containing certificate and key files and then starts a download. Although the archive remains on the SRM (/usr/syno/etc/ssl/.gen/archive.zip) and can be downloaded via SFTP, it only gets updated by clicking on the export button again.

Maybe synology_srm has problems with the download action? Or is the a bug in the SRM's API?

**Comment by aerialls** [comment]
Hello,

Thanks for the issue. 

The API documentation for the Synology SRM is not public, so response codes are not clear... I'll try to see how we can improve this situation with the endpoint.

One thing sure is that the current implementation supports only JSON responses. We'll need to make the system more agile.

I'll try to have a look tonight.

**Comment by aerialls** [comment]
After some investigations, your issue is coming from a missing `file` parameter in your request. I saw this kind of error during my debugs. 

I've added a new API endpoint to download the certificate with `client.core.export_certificate()`.  I've also renamed all API endpoints to prefix the action.

**Comment by stylon** [comment]
Thanks a lot for your prompt response and for fixing this! I love your work and the synology_srm package, as it is easy to use and great help accessing SafeAccess and Network statistics from a remote machine.
