### ISSUE TITLE
Error 402 Permission Denied

### ISSUE THREAD

**Issue by MaxCarritt** [aerialls/synology-srm#20]
Hi, great work and thank you. 

I'm getting an 'http.SynologyApiError: Permission denied (error=402)'

Is there something on the router I need to enable? I checked the auto block list and nothing was blocked. I've turned off 2 factor authentication, and I know I have the password right. 

I've also tried using postman to try and login, and I've also got the same error, so probably nothing wrong with your code, just wondering if you have any ideas.

Also, did you just reverse engineer all of this? I can't find any official documentation on the SRM api.

**Comment by aerialls** [comment]
Hello @MaxCarritt, thanks!

Are you using the account created during the first login? Permissions needed for the API are only available for the first "admin" account. 

Indeed, there is no public API documentation available... I did some reverse-engineering for some endpoints and the authentication is the same as for DSM 😃

**Comment by MaxCarritt** [comment]
Thanks for the quick reply. 

I am using the admin account. 

Hrm yeah I was looking at the DSM api docs and it looked very similar. 

So there's nothing that needs to happen in the router configuration for the API to work?

**Comment by MaxCarritt** [comment]
Today I realized that even though I turned off 2 factor auth, you still have to click on the admin account and click reset multi factor authentication to turn it off for a use that already had it on. I got it working! Thanks again.

**Comment by MaxCarritt** [comment]
Sorry to bother again, but doo you have any idea how long the session id key is good for?
