### ISSUE TITLE
Feature request: Add full endpoint API support.

### ISSUE THREAD

**Issue by bugbiteme** [aerialls/synology-srm#22]
This is very cool. I'm a newb trying to get this to work. I am trying to manually pass in an API endpoint to http.call(), which isn't currently supported with your library. Wish there was more documentation out there.

**Comment by aerialls** [comment]
Hello @bugbiteme,
It should be possible with the following code.
```python
import synology_srm

client = synology_srm.Client(
    host='192.168.1.254',
    port=8001,
    https=True,
    username='admin',
    password='admin',
)

response = client.http.call(
    endpoint='entry.cgi',
    api='SYNO.Core.System.Utilization',
    method='get',
    version=1,
)
```

You can replace the `api` and `method` parameter and you'll receive a JSON payload from the API. I'll add an example in the readme.

**Comment by aerialls** [comment]
I've added a new section in the README to address this question.
