### ISSUE TITLE
Adding monitoring wired devices

### ISSUE THREAD

**Issue by nelbs** [aerialls/synology-srm#6]
I am trying to monitor (homeassistant srm component) all the devices which are connected to my synology router.  It seems to me that only the wireless connected devices are monitored. I this true?

Is it possible to add this to this package so all the devices are monitored? Or doesnt allow the synology API this?

Thanks in advance

Nick

**Comment by aerialls** [comment]
Hi!

You are right. I'll try to add non-wireless devices and surely add an option to select them with Home-Assistant or not.

**Comment by aerialls** [comment]
I've added a new endpoint `SYNO.Core.Network.NSM.Device` to fetch devices (connected or not). I'll release a new version in the weekend and a PR to Home-Assistant.

**Comment by nelbs** [comment]
Awesome! thanks!

**Comment by aerialls** [comment]
The `0.0.7` version has been released.
